$(document).ready(function(){
	$("#apples").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/apples.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#ahiTuna").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/ahiTuna.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#babyCarrots").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/babyCarrots.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#bacon").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/bacon.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#bananas").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/bananas.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#brie").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/brie.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#cherryTomato").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/cherryTomato.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#chicken").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/chicken.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#gnocchi").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/gnocchi.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#hotdog").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/hotdog.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#kiwi").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/kiwi.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#lasagne").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/lasagne.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#mahiMahi").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/mahiMahi.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#manila").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/manila.jpg");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#okra").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/okra.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#penne").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/penne.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#salmon").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/salmon.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#steak").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/steak.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#swissCheese").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/swissCheese.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#tomato").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/tomato.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#trout").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/trout.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#kiwi2").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/kiwi.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#lasagne2").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/lasagne.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#mahiMahi2").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/mahiMahi.png");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})

$(document).ready(function(){
	$("#manila2").click(function(){
		$("#currentImg").fadeOut();
		setTimeout(function(){
			$("#currentImg").attr("src","derekPlusMedia/groceryImgs/manila.jpg");
			$("#currentImg").fadeIn("fast");
		},1000);
	});
})